# Generated by Django 3.0.6 on 2020-10-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='chef',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='menu',
            field=models.CharField(default='', max_length=50),
        ),
    ]
